spring:
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password: 317105678Aa
    #链接超时时间 ms
    timeout: 4000
    #线程池配置
    lettuce:
      pool:
        # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认 -1
        max-wait: -1
        # 连接池最大连接数（使用负值表示没有限制） 默认 8
        max-active: 8
        # 连接池中的最小空闲连接 默认 0
        min-idle: 0
        # 连接池中的最大空闲连接 默认 8
        max-idle: 8
